// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZnM_owLbZRqTSYd2M1_7x8VwVL6MpAkY',
    appId: '1:743090792850:web:82f8c756af226ce61e794b',
    messagingSenderId: '743090792850',
    projectId: 'ai-based-bug-detection',
    authDomain: 'ai-based-bug-detection.firebaseapp.com',
    storageBucket: 'ai-based-bug-detection.firebasestorage.app',
    measurementId: 'G-8JG8QJ4ZY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVwEaa9LelLeViiwmKrqYAEB8vHACupt4',
    appId: '1:743090792850:android:9f05c943a24a44681e794b',
    messagingSenderId: '743090792850',
    projectId: 'ai-based-bug-detection',
    storageBucket: 'ai-based-bug-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzuTGmZoGniPM_5c3i4qX578GjZX1j4k',
    appId: '1:743090792850:ios:bb1c951ea82982291e794b',
    messagingSenderId: '743090792850',
    projectId: 'ai-based-bug-detection',
    storageBucket: 'ai-based-bug-detection.firebasestorage.app',
    iosBundleId: 'com.bugrisk.bugRiskFrontend',
  );
}
